finalproj/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index", as: "home"
  get 'users/index', to:"users#index"
  get 'users/ownpage', to: 'users#ownpage', as: "ownpage"
  get 'posts/create', to:"posts#create"
  get 'posts/new', to: "posts#new", as: "posts_new"
  get 'posts/destroy', to: "posts#destroy", as: "posts_destroy"
  post 'boards/show/:id', to:"posts#create"
  get 'boards/new', to: 'boards#new', as: 'boards_new'
  #get '/boards/create', to:"boards#create"
  get 'users/ownpage/:id', to:"users#ownpage"
  get 'posts/index', to: "posts#index", as: 'posts_index'
  get 'boards/index', to: "boards#index", as: 'boards_index'
  get 'boards/show/:id', to: 'boards#show', as: 'boards_show'
  get 'posts/show/:id', to: 'posts#show', as: 'posts_show'
  patch 'boards/create', to: 'boards#index'
  post 'boards/index', to: 'boards#create'
  patch 'posts/like', to: 'posts#like', as: 'like_post'
  patch 'posts/unlike', to: 'posts#unlike', as: 'unlike_post'
  patch 'boards/show', to: 'boards#subscribe', as: 'board_subscribe'
  patch 'boards/show', to: 'boards#unsubscribe', as: 'board_unsubscribe'


end

finalproj/app/models/achievement.rb
class Achievement < ApplicationRecord
	has_and_belongs_to_many :user
end

finalproj/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

finalproj/app/models/board.rb
class Board < ApplicationRecord
	has_many :posts
	has_and_belongs_to_many :users
	paginates_per 10
end

finalproj/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

finalproj/app/models/post.rb
class Post < ApplicationRecord
	paginates_per 10
	belongs_to :board
	belongs_to :user
	has_many :favorites
	has_many :users, :through => :favorites
	has_many :comments, class_name: "Post", foreign_key: "parent_id"
	belongs_to :parent, class_name: "Post", optional: true
end

finalproj/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, uniqueness: true
  has_many :posts
  has_many :favorites
  has_and_belongs_to_many :boards
  has_and_belongs_to_many :achievements

end

finalproj/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

end

finalproj/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

finalproj/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def new
		@board = Board.new
	end

	def create
		@board = Board.new
		@board.update(board_params)
		current_user.boards << @board
		if @board.save
			redirect_to boards_show_path(@board)
		end
	end

	def index
		@boards = Board.page(params[:page])
	end

	def show
		@board = Board.find(params[:id])
		@posts =  @board.posts.where(parent_id: nil).page(params[:page])
	end

	def subscribe
		@board = Board.find(params[:board])
		#debug test
		if current_user.boards.include?(@board)
			redirect_to '/'
		else
			current_user.boards << @board
			redirect_to boards_show_path(@board)
		end
	end

	def unsubscribe
		@board = Board.find(params[:board])
		current_user#boards.delete(@board)
		current_user.save
		redirect to 'root'
	end

	private

	def board_params
		params.require(:board).permit(:name)
	end
end

finalproj/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

end

finalproj/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @userBoards = current_user.boards.page(params[:page])
    else
      @userBoards = nil
    end
  end

end

finalproj/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post = Post.new
		@current_board = Board.find(params[:board])
	end

	def achieve(user, achievement)
		prize = Achievement.where(name: achievement).first
		if not user.achievements.include?(prize)
			user.achievements << prize
			if user == current_user
				flash[:success] = "Achievement unlocked: " + achievement
			end
		end
	end

	def create
		@post = Post.new
		@board = Board.find(params[:id])
		@post.board_id = @board.id
		@post.likes = 0
		@post.update(post_params)
		#idk whats going on with booleans but i havent gotten it to work without doing this
		if params[:comment] == 'true'
			@post.parent_id = params[:parent_id]
		else
			@post.parent_id = nil
		end
		@post.user_id = current_user.id
		@post.save
		current_user.posts << @post
		i = current_user.posts.length
		if i >= 5
			achieve current_user, "FIVE"
		end
		if i>= 10
			achieve current_user, "wow ten!!!"
		end
		if @post.parent_id
			redirect_to posts_show_path(id: @post.parent_id)
		else
			redirect_to boards_show_path(id: @board.id)
		end
	end

	def show
		@post = Post.find(params[:id])
		@board = Board.find(@post.board_id)
		@comments = Post.where({parent_id: params[:id]}).page(params[:page]).per(5)
	end

	def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to boards_show_path(id: @post.board_id)
	end

	def like
		@post = Post.find(params[:id])
		@post.likes += 1
		@author = User.find(@post.user_id)
		@author.point += 1
		achieve @author,"Likeable"

		@favorite = @post.favorites.create(user_id: current_user.id, post_id: @post.id)
		@author.save
		@post.save

		red_id = @post.parent_id
		if red_id == nil
			red_id = @post.id
		end
		redirect_to posts_show_path(id: red_id)
	end

	def unlike
		@post = Post.find(params[:id])
		@post.likes -= 1
		if @post.likes<0
			@post.likes = 0
		end
		@author = User.find(@post.user_id)
		@author.point -= 1
		achieve @author, "Unlikeable"
		@favorite = @post.favorites.where(user_id: current_user.id).delete_all
		@author.save
		@post.save

		red_id = @post.parent_id
		if red_id == nil
			red_id = @post.id
		end
		redirect_to posts_show_path(id: red_id)
	end

	private
	def post_params
		params.require(:post).permit(:title, :content)
	end
end

finalproj/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

finalproj/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def ownpage
		@user = User.find(params[:user_id])
		@userPosts = @user.posts.where(parent_id: nil).page(params[:page])
	end
end

finalproj/app/helpers/application_helper.rb
module ApplicationHelper
end

finalproj/app/views/boards/create.html.erb
<%= simple_form_for @board, url: boards_create_path do |f| %>
<%= f.input :name , label:'Your board name please' %>
<%= f.button :submit %>
<% end %>

finalproj/app/views/boards/index.html.erb
<%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>

<h1> All Boards</h1>

 <%= link_to "Home", home_path %>
<hr>
</br>
<% @boards.each do |b|%>
<%= link_to b.name, boards_show_path(b.id) %>
</br>
<% end %>
<% if current_user %>
<%= button_to "Create New Board!", boards_new_path, method: :get %>
<% end %>
</br>
<%= paginate @boards %>

finalproj/app/views/boards/new.html.erb
<%= simple_form_for @board, url: boards_index_path do |f|%>
<%= f.input :name , label:'Your board name please' %>
<%= f.button :submit %>
<% end %>

finalproj/app/views/boards/show.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<div id="header">
<h1> <%= @board.name %> </h1>
</div>
<div class="colmask leftmenu">
	<div class="colleft">
		<div class="col1">
			<!-- for some reason I cannot get this to work with button_to -->
			<% if current_user %>
				<%= link_to "Create New Post", posts_new_path(board: @board.id, comment: :false), method: :get%>
			<% end %>
			<h2>Posts</h2>
<% @posts.each do |p|%>
	<%= link_to p.title, posts_show_path(id: p.id) %>
	<br>
<% end %>
<%=paginate @posts%>
</div>
<div class = "col2">

</div>
</div>
</div>
<div id="footer">
	<% if current_user and current_user.boards.include?(@board) %>
		<!-- does not work for some reason, board still shows up on home screen -->
		<%= link_to "Unsubscribe", board_unsubscribe_path(board: @board.id), method: :patch %>
	<% else %>
		<%= link_to "Subscribe", board_subscribe_path(board: @board.id), method: :patch %>
	<% end %>
	<%= link_to "Home", home_path %>
</div>

finalproj/app/views/home/index.html.erb
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>


<div id = "header">
  <% if current_user %>
	<h1 align = "center">Welcome to the message board, <%=current_user.name%>! </h1>
  <% else %>
	<h1 align = "center">Welcome to the message board! </h1>
  <% end %>
</div>
<body>

<% if current_user%>
<div class="colmask leftmenu">
	<div class="colleft">
		<div class="col1">
		<h2> My Boards </h2>
    <hr>
		<% @userBoards.each do |t| %>
			 <%= link_to t.name, boards_show_path(t.id) %>
			</br>
		<% end %>
    <hr>
    <%=paginate @userBoards %>
	<% end %>
	</div>
	<div class = "col2">
	<% if current_user%>
</br>
    <%= link_to "Create New Board!", boards_new_path, method: :get %>
</br>
		<%= link_to "See all boards", boards_index_path %>
    <hr>
    <h1>Leaderboard</h1>
    <% User.all.sort_by(&:point).reverse.each do |u|%>
      <%=link_to u.name, ownpage_path(:user_id => u.id)%>, Points: <%=u.point%> </br>
    <%end%>
    <hr>
    <%= link_to "View my profile", ownpage_path(:user_id => current_user.id) %>
		<%= button_to 'Logout', destroy_user_session_path, method: :delete %>
	<% end %>
	</div>
  </div>
</div>
<div class = "footer">
	<% if not current_user %>

		<%= button_to "Sign up for free", new_user_registration_path, method: :get %>
		</br>
		<%= button_to "Sign in", new_user_session_path %>
	<% end %>
</div>

</body>

finalproj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finalproj</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

finalproj/app/views/posts/create.html.erb
<%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= simple_form_for @post, url: posts_create_path do |f| %>
<%= f.input :title , label:'Your post title please' %>
<%= f.input :content , label:'Your post content please', size: '60*12' %>
<%= f.button :submit %>
<% end %>

finalproj/app/views/posts/index.html.erb
<%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>

<% @posts.each do ||

finalproj/app/views/posts/new.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div id = "header">
<h1 align = "center"><%= @current_board.name %></h1>
</div>
<%= simple_form_for @post, url: boards_show_path(id: @current_board, comment: params[:comment], parent_id: params[:parent_id]) do |f| %>
<!-- some really jank shit here -->
  <% if params[:comment] == 'false'%>
    <%= f.input :title , label:'Post Title: ' %>
  <% end %>
  <%= f.input :content , label:'Content: ', size: '420*69' %>
  <%= f.button :submit %>
  <%= link_to "Cancel", home_path %>
<% end %>

finalproj/app/views/posts/show.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<body>

<div id="header">
	  <h1><%= link_to @board.name, boards_show_path(@board.id) %></h1>
</div>
<div class="colmask leftmenu">
	<div class="colleft">
		<div class="col1">
			<h2>Comments</h2><hr>
			<% @comments.each do |p| %>
				<%= p.content %> </br>
				<% @cauthor = User.find(p.user_id) %>
				<%= link_to @cauthor.name, ownpage_path(:user_id => @cauthor.id) %>
				Likes: <%= p.likes %>
				<% if current_user %>
					<!-- debug: for some reason user_id of post seems to change when you switch users, and posts can't be liked -->
					<% if not(p.users.include?(current_user) or p.user_id == current_user.id) %>
							<%= link_to "Like", {controller: "posts", action: "like", id: p.id}, :method => :patch %>
					<% end %>
					<% if p.users.include?(current_user) %>
							<%= link_to "Unlike", {controller: "posts", action: "unlike", id: p.id}, :method => :patch %>
					<% end %>
					<% if current_user and  p.user_id == current_user.id %>
				</br>
						<%= link_to "Delete Comment", posts_destroy_path(id: p.id), data:{:confirm => "Are you sure you want to permanently delete your post?"}%>
					<%end%>
					<hr>
				<% end %>
			<% end %>
			<%=paginate @comments%>
<%= link_to "Add Comment", posts_new_path(comment: true, parent_id: @post.id, board: @post.board_id) %>
		</div>
		<div class="col2">

				<h3> <%= @post.title %> </h3>
				<%= @post.content %>
				<% @author = User.find(@post.user_id) %>
				<%= link_to @author.name, ownpage_path(:user_id => @author.id) %>
				</br>
				Likes: <%= @post.likes %>
				<% if current_user and  @post.user_id == current_user.id %>
					<%= link_to "Delete Post", posts_destroy_path(id: @post.id), data:{:confirm => "Are you sure you want to permanently delete your post?"}%>
				<%end%>
				<% if current_user and not(@post.users.include?(current_user) or @post.user_id == current_user.id) %>
				<!-- post.users signifies users who liked a post, so that they can't like the same post twice -->
					<%= link_to "Like", {controller: "posts", action: "like", id: @post.id}, :method => :patch %>
				<% end %>
				<% if @post.users.include?(current_user) %>
						<%= link_to "Unlike", {controller: "posts", action: "unlike", id: @post.id}, :method => :patch %>
				<% end %>

		</div>
	</div>
</div>
</body>

finalproj/app/views/users/index.html.erb
<%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>
<% @users.each do |user|%>
<tr>
<%= render user %>
</tr>
<% end %>

finalproj/app/views/users/ownpage.html.erb
<%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>

<h2>User Info</h2>
<p>Name: <%= @user.name  %> </p>


<p>Email: <%= @user.email if @user.email %></p>
<p>Points: <%= @user.point %> </p>
<p>Joined: <%= @user.created_at %> </p>
<h2> Posts </h2>
<p> <% @userPosts.each do |t| %>
	<%= link_to t.title, posts_show_path(t.id) %> </br>
	<% end %>
	<%=paginate @userPosts%>
</br>
<h2>Achievements</h2>
<% if @user.achievements.length == 0%>
<p>No achievements unlocked yet!</p>
<%end%>
<% @user.achievements.each do |t| %>
	<p><i><%= t.name %></i></p>
	<h6><i> <%= t.description %> </i></h6>
	<% end %>
</br>
<%= link_to "Home", home_path %>